name: React Application Setup
on:
  push:

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
    
      - name: printing test message
        run: echo "Learning GitHub Actions"
      - name: Checking current directory
        run:  pwd
   
